#version of the docker compose syntax
# version: "3.9"


services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
    #mapping the directories in our system to app container
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"    
